name = "backend"
main = "src/index.ts"
compatibility_date = "2025-01-29"

# compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNGU0MGQ4YTktYTk4MS00YTI1LWJhMDktMGM0Zjg4NTBjZTFhIiwidGVuYW50X2lkIjoiNTNkMDJkZTkzNmRkZGJlMGU0ZjAwNTJjOWVhYzAwNDNiZDcxZTBlNGE0MjlmZDM1MjI5MmM4Yzk4OWVjMGZkNSIsImludGVybmFsX3NlY3JldCI6Ijk1MDI5OTgxLWI0MjktNGQwOS1hMTYwLTIzNDhkZmMxMjBhYyJ9.vjkiUCDLbw1cAbsogMgGTqgbMdD4tEZ59BRXL83ObKI"
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
JWT_SECRET="asdj&nh&Ghjsdil!@(N*Nfs)dfj>UNI"
# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1