export enum ErrorCodes {
    USER_EXISTS = "USER_EXISTS",
    USER_NOT_FOUND = "USER_NOT_FOUND",
    INVALID_PASSWORD = "INVALID_PASSWORD",
    INTERNAL_ERROR = "INTERNAL_ERROR",
    MUST_BE_LOGGED_IN = "MUST_BE_LOGGED_IN",
    TOKEN_EXPIRED = "TOKEN_EXPIRED_",
    INVALID_TOKEN = "INVALID_TOKEN"
}

